- hosts: all
  remote_user: ec2-user
  tasks:
      - name: install docker
        yum:
          name: docker
          state: latest
      - name: start docker
        command: service docker start
      - name: run pacman
        command: docker run -p 80:80 -d codeherent/pacman
